"use client";
import {useEffect,useId,useRef,useState} from "react";import {Input} from "./input";import {Button} from "./button";import {FormField} from "../forms/form-field";
export type Option={id:string;label:string};
export type OptionPage={options:Option[];hasMore:boolean};
export type OptionLoader=(query:string,page:number,signal:AbortSignal)=>Promise<OptionPage>;
export function Combobox({label,value,onChange,loadOptions,disabled=false,readOnly=false,help}:{label:string;value:Option|null;onChange:(value:Option|null)=>void;loadOptions:OptionLoader;disabled?:boolean;readOnly?:boolean;help?:string}){
 const id=useId();const [query,setQuery]=useState("");const [open,setOpen]=useState(false);const [page,setPage]=useState(0);const [retry,setRetry]=useState(0);const [result,setResult]=useState<OptionPage>({options:[],hasMore:false});const [status,setStatus]=useState<"loading"|"ready"|"error">("loading");const [active,setActive]=useState(-1);const generation=useRef(0);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const controller=new AbortController();const current=++generation.current;if(!open||disabled||readOnly)return ()=>controller.abort();loadOptions(query,page,controller.signal).then(data=>{if(!controller.signal.aborted&&current===generation.current){setResult(previous=>({options:page?[...previous.options,...data.options]:data.options,hasMore:data.hasMore}));setStatus("ready");}},()=>{if(!controller.signal.aborted&&current===generation.current)setStatus("error");});return ()=>controller.abort();},[query,page,retry,open,disabled,readOnly,loadOptions]);
 const choose=(option:Option)=>{onChange(option);setOpen(false);setQuery("");setPage(0);setActive(-1);input.current?.focus();};
 const begin=()=>{setOpen(true);setStatus("loading");setActive(-1);setPage(0);};
 return <FormField label={label} help={help}>{field=><div className="combobox" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget)){setOpen(false);setQuery("");setPage(0);}}}><Input {...field} ref={input} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={open?`${id}-list`:undefined} aria-activedescendant={open&&active>=0&&status==="ready"?`${id}-${active}`:undefined} autoComplete="off" disabled={disabled} readOnly={readOnly} value={open?query:value?.label??""} onFocus={()=>{if(!readOnly)begin();}} onClick={()=>{if(!open&&!readOnly)begin();}} onChange={e=>{setQuery(e.target.value);setPage(0);setStatus("loading");setActive(-1);setOpen(true);}} onKeyDown={e=>{if(readOnly)return;if(e.key==="Escape"){e.preventDefault();setOpen(false);setQuery("");}if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();if(!open)begin();else if(status==="ready")setActive(a=>e.key==="ArrowDown"?Math.min(a+1,result.options.length-1):Math.max(a-1,0));}if(e.key==="Enter"&&open){e.preventDefault();if(status==="ready"&&active>=0)choose(result.options[active]);}}}/>{value&&!disabled&&!readOnly&&<Button variant="ghost" size="sm" onClick={()=>{onChange(null);setQuery("");}}>Clear {label}</Button>}{open&&<div className="combo-popup"><ul id={`${id}-list`} role="listbox" aria-label={label} aria-busy={status==="loading"}>{status==="ready"&&result.options.map((option,index)=><li key={option.id} id={`${id}-${index}`} role="option" aria-selected={value?.id===option.id} data-active={active===index} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(option)}>{option.label}</li>)}</ul>{status==="loading"&&<p role="status">Loading options…</p>}{status==="error"&&<div role="alert">Could not load options. <Button variant="outline" onClick={()=>{setStatus("loading");setRetry(r=>r+1);}}>Retry options</Button></div>}{status==="ready"&&!result.options.length&&<p role="status">No matching options</p>}{status==="ready"&&result.hasMore&&<Button variant="ghost" onClick={()=>{setStatus("loading");setActive(-1);setPage(p=>p+1);}}>Load more options</Button>}</div>}</div>}</FormField>;
}
